[package]
name = "glyphify"
version = "0.1.0"
edition = "2021"
authors = ["eyelyd"]
description = "images to html"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
base64 = "0.22.1"
clap = { version = "4.5.1", features = ["derive"] }
fontdue = "0.9.3"
image = "0.25.1"
